* XUnit
"객체"에 관한 책을 읽었다.
정말 쉬운 내용이다. 내용이랄 것도 없는 것이 저자가 책을 쓴 의도가 다음에 출간할 "객체에 관한 책을 읽을 독자"들을 위해 객체 지향 프로그램에서 사용하는 용어와 개념에 대한 설명을 쉽게 풀어놓은 까닭이다.
헌데 잘 안 읽혔다. 읽어도 머리 속에 잡히는 가닥이 없고, 읽은거나 안 읽은거나 동일한 느낌이라 굉장히 어렵게 꼬박 하루를 투자해서 억지로 읽었다.
다 읽고나니, 역시 다 알만한 내용 - 객체 지향 프로그래밍 - 에 관한 프로그래머라면 당연히 알아야 하는 개념과 용어에 대한 일반적인 때로는 독창적인 설명이다.

하지만, 이 책이 전하려는 객체에 관한 기본 지식이 우리 딸에게는 상당한 도움이 될꺼라는 생각이 들었다. 그래서 딸을 위해 Scan을 떴다. 아빠의 성의를 봐서라도 꼭 읽기 바란다!
이 책으로 "Spring MVC 학습 Curriculum" 중 "Java 언어" 파트의 <interface> 와 <class>에 대한 수업을 대체한다. 네가 이 책의 "객체 지향 프로그래밍" 기법을 알고, 실무에서 사용할 수 있다면, 그 날로 너의 인건비는 2배 이상 인상이 될 걸 보장하마~

이 책을 읽으면서, 저자가 가끔씩 TDD에 대해서 얘기할 때마다 계속 호기심이 생겼다. TDD가 뭐길래 이렇게 틈만 나면 강조를 할까? 결국, 답답함을 해소하기 위해 Test Driven Development를 찾아 보았다.
JUnit가 뭔지 아는가? JUnit을 누가 만들었는지 아는가?
켄트 백이다.
이 넘과 JUnit에 관한 재미있는 얘기를 들려 주마~

JUnit는 "현재 전 세계적으로 가장 널리 사용되는 Java의 단위 테스트 프레임워크”라고 소개되고 있는데, 이 JUnit의 탄생 과정을 얘기할까 한다.
수빈이 네가 태어나기 한 해 전에, 켄트 벡 (Kent Beck)과 "디자인 패턴" 이란 유명한 책을 쓴 4 명의 공동 저자 중 한 명인 에릭 감마가 우연한 기회에 같이 비행기를 타고 유럽에서 미국의 OOP 관련 세미나에 참석하러 가게 되면서 시작된 일이다.

두 넘의 프로그램 밖에 모르는 Geeks 가 미국으로 가는 지루한 시간 동안 비행기에서 뭘 했겠니?
이런 저런 얘기를 나누다가 캔트 벡이 자기는 프로그램을 짤 때는 항상 테스트 루틴을 먼저 짜고, 테스트가 실패한 경우만 프로그램이 정상 동작하도록 코딩을 한다는 얘기를 했다.
이처럼 테스트 위주의 프로그램이 가능하도록 새로운 프로젝트를 진행할 때마다 매 번 프로젝트 성격에 맞는 새로운 단위 테스트 프로그램부터 짠다고 얘기했단다. 자기는 SmallTalk 용 단위 테스트 프로그램만 수 십번을 짜서, 이제는 SUnit 프로그램 제작 전문가라고 자랑을 했지.

이 얘기를 듣고 에릭 감마가 혹시 Java에서 사용 가능한 단위 테스트 프로그램도 짤 수 있냐고 했지. 하지만, 켄트 벡은 자기는 Java를 모른다고 얘기했지.
그래서 에릭 감마가 딜을 걸었단다. "야, 켄트! 네가 테스트 주도 개발을 그렇게 잘 한다면, 자바에서 사용할 수 있는 단위 테스트 프로그램을 네가 평상 시 짜던 방식으로 짜 봐! 대신 내가 너한테 자바 언어로 프로그램하는 법을 알려 줄께.. 미국까지 지루하게 가는 것보단 서로 같이 새로운 것도 배우고 좋지 않겠냐?"

이렇게 해서 에릭은 켄트에게 Java 언어를 가르쳐 주고, 켄트는 새롭게 배운 Java 언어를 이용해서 "테스트 주도 개발"이 가능하도록 도와주는 "단위 테스트 프로그램"을 "테스트 주도 개발 기법"을 사용해서 작성했단다. 그렇게 비행기에서 완성된 프로그램을 나중에 켄트 벡이 자바 세계에 무료로 쓰라고 발표했는데, 이 프로그램이 바로 공전의 히트를 친 "JUnit" 이란다.
마틴 파울러는 "소프트웨어 공학 역사에서 이토록 많은 사람이 이렇게 짧은 코드로 이토록 큰 은혜를 입은 적이 없었다"고 말하기도 했고, JUnit을 시작으로 해서 CUnit, CppUnit, PyUnit 등 xUnit 프레임워크가 탄생하게 된거지~ 어때 놀랍지 않니?

그 이후로 켄트 벡은 틈만 나면 이런 소리를 지껄였단다. "난 새로운 프로그래밍 언어를 처음 접하면 그 언어로 xUnit을 만들어 본다. 테스트가 여덟 개에서 열 개 정도 통과할 때쯤이면 그 언어로 프로그래밍하면서 접하게 될 많은 기능을 한 번씩 경험해보게 된다. 니들도 새로운 언어를 배울때는, 그 언어로 xUnit을 짜봐! 헤헤~"
더구나 나중엔 자바 언어로 테스트 주도 개발을 하는 방법을 실예로 보여주고, 파이썬을 처음 공부하면서 파이썬으로 JUnit과 유사한 단위 테스트 도구를 작성하는 과정을 세밀하게 책으로 기술해서 세상에 발표했단다. 그 책이 바로 "Test Driven Development by Example" 이란다.

아빠도 이 책을 한 번 쭉 따라해봤단다. 정말 재미있더구나.
난생 처음 배운 언어로 "테스트 주도 개발 기법"을 사용해서 "테스트 주도 개발을 하기 위한 툴"을 만든다니...
켄트 벡의 말처럼 : "테스트 툴을 만드는 과정에서 만들어지는 테스트 툴 자체를 사용한다는 것은 스스로 자신의 뇌를 수술하는 것과 비슷할 것 같다. ("거기 있는 운동 중추는 건들면 안돼, 오 이런, 죽었네.") 때때로 괴상해지기도 할 것이다." 이런 걸 자기 참조 프로그램 이라고 하기도 하는 모양인데, 먼저 테스트 케이스를 만들고, 테스트 메서드를 실행할 수 있도록 프로그램하는 방식이 너무 재미있고 흥미진진했단다.

수빈이 너도 흥미를 느낀다면, 집에 와서 아빠 컴퓨터에서 니 손으로 JUnit 라이브러리를 한 번 작성해보면 어떨까 싶다.
네가 태어나기 전, 켄트 벡과 에릭 감마가 비행기에서 작성했던 JUnit 프로그램 작성 과정을 아빠와 함께 그대로 따라해 보자는 얘기다.
요즘은 JUnit5가 많이 사용되지만, 그건 코드가 너무 복잡할테고, JUnit3 정도의 기능을 가지고 있는 라이브러리라면 별로 힘이 들지 않을 거라 생각한다.
아빠는 네가 직접 짜서 Java 개발에 사용할 수 있는 JUnit3 정도의 라이브러리를 짜는데 "테스트 주도 개발"이라는 방법을 어떻게 사용하는지 알려 주마~
"객체 지향의 사실과 오해" 정도는 읽고 오기 바란다. 서로 대화가 통하려면, 기본 용어로 설명할 때, 그게 무슨 말인지는 이해할 수 있어야 하니까~

Java로 짜는 TapTap이는 TDD 방식으로 짜기로 결정했따. 물론, 네가 짜겠다고 이런저런 노력을 할 경우의 얘기겠지만...
일단은 네가 자신있게 Junit3 라이브러리 짜러 오겠다는 말을 기다리마~

** Java에서 사용할 XUnit like Junit3 ?
예를 들면 TestCase("testMethod").run()

*** 테스트 작성 시, 공통된 패턴 3A
1. 준비(Arrange) : 객체를 생성한다.
2. 행동(Act) : 객체에 메시지를 주어 테스트한다.
3. 확인(Assert) : 결과를 검사한다.

*** ToDo
우린 테스트 케이스를 작성하기 위해 사용할 프레임 워크를 테스트하기 위한 테스트 케이스를 작성해야 하는 것이다.
아직 프레임워크가 없기 때문에 첫 번째 작은 단계는 수동으로 검증해야 할 것이다.
머릿 속에 떠오른 테스트 프레임워크에 대한 할 일 목록이다.
- 테스트 메서드 호출하기
- 먼저 setUp 호출하기
- 나중에 tearDown 호출하기
- 테스트 메서드가 실패하더라도 teadDown 호출하기
- 여러 개의 테스트 실행하기
- 수집된 테스트 결과를 출력하기

